### ISSUE TITLE
bug affichage _serverlist


### ISSUE THREAD

**Issue by Betawolfy** [betawolfy/botty-anti-hack-bdscript#2]
les émojis de succès dans _serverlist ne s'affiche pas.

**Comment by Betawolfy** [comment]
il faut totalement changer les emoji:
emoji custom => emoji discord.
Je pense que le bug viens du bdscript.

**Comment by rastiqdev** [comment]
Oui, le bug vient du BDScript. (plus d'infos dans l'issue 7)
