### ISSUE TITLE
bug affichage _optiwork

### ISSUE THREAD

**Issue by Betawolfy** [betawolfy/botty-anti-hack-bdscript#7]
les émoji customs ne s'affiche que sur le serveur support.

**Comment by rastiqdev** [comment]
C'est un bug du bdsrcipt. Le BDScript va chercher les emojis custom du seveur où LE MESSAGE EST ENVOYÉ. C'est à dire que si on met les emojis du serveur dans les autres serveurs, cela devrait régler le problème.

**Comment by rastiqdev** [comment]
Ou alors remplacer les emotes par des emotes intégrées à discord.
